package sa.revenue.general.db;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "ADMOB_DAY".
 */
public class AdmobDay {

    private Long id;
    private String Date;
    private String AdRequests;
    private String AdRequestsCoverage;
    private String Clicks;
    private String CostPerClick;
    private String Earnings;
    private String IndividualAdImpressions;
    private String IndividualAdImpressionsCtr;
    private String IndividualAdImpressionsRpm;
    private String MatchedAdRequests;
    private String MatchedAdRequestsCtr;
    private String MatchedAdRequestsRpm;
    private String PageViews;
    private String PageViewsCtr;
    private String PageViewsRpm;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public AdmobDay() {
    }

    public AdmobDay(Long id) {
        this.id = id;
    }

    public AdmobDay(Long id, String Date, String AdRequests, String AdRequestsCoverage, String Clicks, String CostPerClick, String Earnings, String IndividualAdImpressions, String IndividualAdImpressionsCtr, String IndividualAdImpressionsRpm, String MatchedAdRequests, String MatchedAdRequestsCtr, String MatchedAdRequestsRpm, String PageViews, String PageViewsCtr, String PageViewsRpm) {
        this.id = id;
        this.Date = Date;
        this.AdRequests = AdRequests;
        this.AdRequestsCoverage = AdRequestsCoverage;
        this.Clicks = Clicks;
        this.CostPerClick = CostPerClick;
        this.Earnings = Earnings;
        this.IndividualAdImpressions = IndividualAdImpressions;
        this.IndividualAdImpressionsCtr = IndividualAdImpressionsCtr;
        this.IndividualAdImpressionsRpm = IndividualAdImpressionsRpm;
        this.MatchedAdRequests = MatchedAdRequests;
        this.MatchedAdRequestsCtr = MatchedAdRequestsCtr;
        this.MatchedAdRequestsRpm = MatchedAdRequestsRpm;
        this.PageViews = PageViews;
        this.PageViewsCtr = PageViewsCtr;
        this.PageViewsRpm = PageViewsRpm;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getDate() {
        return Date;
    }

    public void setDate(String Date) {
        this.Date = Date;
    }

    public String getAdRequests() {
        return AdRequests;
    }

    public void setAdRequests(String AdRequests) {
        this.AdRequests = AdRequests;
    }

    public String getAdRequestsCoverage() {
        return AdRequestsCoverage;
    }

    public void setAdRequestsCoverage(String AdRequestsCoverage) {
        this.AdRequestsCoverage = AdRequestsCoverage;
    }

    public String getClicks() {
        return Clicks;
    }

    public void setClicks(String Clicks) {
        this.Clicks = Clicks;
    }

    public String getCostPerClick() {
        return CostPerClick;
    }

    public void setCostPerClick(String CostPerClick) {
        this.CostPerClick = CostPerClick;
    }

    public String getEarnings() {
        return Earnings;
    }

    public void setEarnings(String Earnings) {
        this.Earnings = Earnings;
    }

    public String getIndividualAdImpressions() {
        return IndividualAdImpressions;
    }

    public void setIndividualAdImpressions(String IndividualAdImpressions) {
        this.IndividualAdImpressions = IndividualAdImpressions;
    }

    public String getIndividualAdImpressionsCtr() {
        return IndividualAdImpressionsCtr;
    }

    public void setIndividualAdImpressionsCtr(String IndividualAdImpressionsCtr) {
        this.IndividualAdImpressionsCtr = IndividualAdImpressionsCtr;
    }

    public String getIndividualAdImpressionsRpm() {
        return IndividualAdImpressionsRpm;
    }

    public void setIndividualAdImpressionsRpm(String IndividualAdImpressionsRpm) {
        this.IndividualAdImpressionsRpm = IndividualAdImpressionsRpm;
    }

    public String getMatchedAdRequests() {
        return MatchedAdRequests;
    }

    public void setMatchedAdRequests(String MatchedAdRequests) {
        this.MatchedAdRequests = MatchedAdRequests;
    }

    public String getMatchedAdRequestsCtr() {
        return MatchedAdRequestsCtr;
    }

    public void setMatchedAdRequestsCtr(String MatchedAdRequestsCtr) {
        this.MatchedAdRequestsCtr = MatchedAdRequestsCtr;
    }

    public String getMatchedAdRequestsRpm() {
        return MatchedAdRequestsRpm;
    }

    public void setMatchedAdRequestsRpm(String MatchedAdRequestsRpm) {
        this.MatchedAdRequestsRpm = MatchedAdRequestsRpm;
    }

    public String getPageViews() {
        return PageViews;
    }

    public void setPageViews(String PageViews) {
        this.PageViews = PageViews;
    }

    public String getPageViewsCtr() {
        return PageViewsCtr;
    }

    public void setPageViewsCtr(String PageViewsCtr) {
        this.PageViewsCtr = PageViewsCtr;
    }

    public String getPageViewsRpm() {
        return PageViewsRpm;
    }

    public void setPageViewsRpm(String PageViewsRpm) {
        this.PageViewsRpm = PageViewsRpm;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
