package sa.revenue.general.db;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import sa.revenue.general.db.App;
import sa.revenue.general.db.AdPlacement;
import sa.revenue.general.db.TapjoyApp;
import sa.revenue.general.db.TapjoyDay;
import sa.revenue.general.db.AdmobAdUnit;
import sa.revenue.general.db.AdmobDay;

import sa.revenue.general.db.AppDao;
import sa.revenue.general.db.AdPlacementDao;
import sa.revenue.general.db.TapjoyAppDao;
import sa.revenue.general.db.TapjoyDayDao;
import sa.revenue.general.db.AdmobAdUnitDao;
import sa.revenue.general.db.AdmobDayDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig appDaoConfig;
    private final DaoConfig adPlacementDaoConfig;
    private final DaoConfig tapjoyAppDaoConfig;
    private final DaoConfig tapjoyDayDaoConfig;
    private final DaoConfig admobAdUnitDaoConfig;
    private final DaoConfig admobDayDaoConfig;

    private final AppDao appDao;
    private final AdPlacementDao adPlacementDao;
    private final TapjoyAppDao tapjoyAppDao;
    private final TapjoyDayDao tapjoyDayDao;
    private final AdmobAdUnitDao admobAdUnitDao;
    private final AdmobDayDao admobDayDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        appDaoConfig = daoConfigMap.get(AppDao.class).clone();
        appDaoConfig.initIdentityScope(type);

        adPlacementDaoConfig = daoConfigMap.get(AdPlacementDao.class).clone();
        adPlacementDaoConfig.initIdentityScope(type);

        tapjoyAppDaoConfig = daoConfigMap.get(TapjoyAppDao.class).clone();
        tapjoyAppDaoConfig.initIdentityScope(type);

        tapjoyDayDaoConfig = daoConfigMap.get(TapjoyDayDao.class).clone();
        tapjoyDayDaoConfig.initIdentityScope(type);

        admobAdUnitDaoConfig = daoConfigMap.get(AdmobAdUnitDao.class).clone();
        admobAdUnitDaoConfig.initIdentityScope(type);

        admobDayDaoConfig = daoConfigMap.get(AdmobDayDao.class).clone();
        admobDayDaoConfig.initIdentityScope(type);

        appDao = new AppDao(appDaoConfig, this);
        adPlacementDao = new AdPlacementDao(adPlacementDaoConfig, this);
        tapjoyAppDao = new TapjoyAppDao(tapjoyAppDaoConfig, this);
        tapjoyDayDao = new TapjoyDayDao(tapjoyDayDaoConfig, this);
        admobAdUnitDao = new AdmobAdUnitDao(admobAdUnitDaoConfig, this);
        admobDayDao = new AdmobDayDao(admobDayDaoConfig, this);

        registerDao(App.class, appDao);
        registerDao(AdPlacement.class, adPlacementDao);
        registerDao(TapjoyApp.class, tapjoyAppDao);
        registerDao(TapjoyDay.class, tapjoyDayDao);
        registerDao(AdmobAdUnit.class, admobAdUnitDao);
        registerDao(AdmobDay.class, admobDayDao);
    }
    
    public void clear() {
        appDaoConfig.getIdentityScope().clear();
        adPlacementDaoConfig.getIdentityScope().clear();
        tapjoyAppDaoConfig.getIdentityScope().clear();
        tapjoyDayDaoConfig.getIdentityScope().clear();
        admobAdUnitDaoConfig.getIdentityScope().clear();
        admobDayDaoConfig.getIdentityScope().clear();
    }

    public AppDao getAppDao() {
        return appDao;
    }

    public AdPlacementDao getAdPlacementDao() {
        return adPlacementDao;
    }

    public TapjoyAppDao getTapjoyAppDao() {
        return tapjoyAppDao;
    }

    public TapjoyDayDao getTapjoyDayDao() {
        return tapjoyDayDao;
    }

    public AdmobAdUnitDao getAdmobAdUnitDao() {
        return admobAdUnitDao;
    }

    public AdmobDayDao getAdmobDayDao() {
        return admobDayDao;
    }

}
