package sa.revenue.general.db;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
import sa.revenue.advertisers.tapjoy.TapjoyUtils;
// KEEP INCLUDES END
/**
 * Entity mapped to table "TAPJOY_DAY".
 */
public class TapjoyDay {

    private Long id;
    private String Date;
    private Integer AppCount;
    private Integer PaidInstallsSum;
    private String PaidInstallsHourlySum;
    private Integer PaidClicksSum;
    private String PaidClicksHourlySum;
    private Double SpendSum;
    private String SpendHourlySum;
    private Integer SessionsSum;
    private String SessionsHourlySum;
    private Integer NewUsersSum;
    private String NewUsersHourlySum;
    private Integer DailyActiveUsersSum;
    private Double OfferwallRevenueSum;
    private String OfferwallRevenueHourlySum;
    private Integer OfferwallImpressionsSum;
    private String OfferwallImpressionsHourlySum;
    private Integer OfferwallClicksSum;
    private String OfferwallClicksHourlySum;
    private Integer OfferwallConversionsSum;
    private String OfferwallConversionsHourlySum;
    private Double FeaturedOfferRevenueSum;
    private String FeaturedOfferRevenueHourlySum;
    private Integer FeaturedOfferImpressionsSum;
    private String FeaturedOfferImpressionsHourlySum;
    private Integer FeaturedOfferClicksSum;
    private String FeaturedOfferClicksHourlySum;
    private Integer FeaturedOfferConversionsSum;
    private String FeaturedOfferConversionsHourlySum;
    private Double TJMOfferwallRevenueSum;
    private String TJMOfferwallRevenueHourlySum;
    private Integer TJMOfferwallImpressionsSum;
    private String TJMOfferwallImpressionsHourlySum;
    private Integer TJMOfferwallClicksSum;
    private String TJMOfferwallClicksHourlySum;
    private Integer TJMOfferwallConversionsSum;
    private String TJMOfferwallConversionsHourlySum;
    private Double DirectPlayRevenueSum;
    private String DirectPlayRevenueHourlySum;
    private Integer DirectPlayImpressionsSum;
    private String DirectPlayImpressionsHourlySum;
    private Integer DirectPlayClicksSum;
    private String DirectPlayClicksHourlySum;
    private Integer DirectPlayConversionsSum;
    private String DirectPlayConversionsHourlySum;

    // KEEP FIELDS - put your custom fields here
    private int[] PaidInstallsHourly;
    private int[] PaidClicksHourly;
    private double[] SpendHourly;
    private int[] SessionsHourly;
    private int[] NewUsersHourly;
    private double[] OfferwallRevenueHourly;
    private int[] OfferwallImpressionsHourly;
    private int[] OfferwallClicksHourly;
    private int[] OfferwallConversionsHourly;
    private double[] FeaturedOfferRevenueHourly;
    private int[] FeaturedOfferImpressionsHourly;
    private int[] FeaturedOfferClicksHourly;
    private int[] FeaturedOfferConversionsHourly;
    private double[] TJMOfferwallRevenueHourly;
    private int[] TJMOfferwallImpressionsHourly;
    private int[] TJMOfferwallClicksHourly;
    private int[] TJMOfferwallConversionsHourly;
    private double[] DirectPlayRevenueHourly;
    private int[] DirectPlayImpressionsHourly;
    private int[] DirectPlayClicksHourly;
    private int[] DirectPlayConversionsHourly;
    // KEEP FIELDS END

    public TapjoyDay() {
    }

    public TapjoyDay(Long id) {
        this.id = id;
    }

    public TapjoyDay(Long id, String Date, Integer AppCount, Integer PaidInstallsSum, String PaidInstallsHourlySum, Integer PaidClicksSum, String PaidClicksHourlySum, Double SpendSum, String SpendHourlySum, Integer SessionsSum, String SessionsHourlySum, Integer NewUsersSum, String NewUsersHourlySum, Integer DailyActiveUsersSum, Double OfferwallRevenueSum, String OfferwallRevenueHourlySum, Integer OfferwallImpressionsSum, String OfferwallImpressionsHourlySum, Integer OfferwallClicksSum, String OfferwallClicksHourlySum, Integer OfferwallConversionsSum, String OfferwallConversionsHourlySum, Double FeaturedOfferRevenueSum, String FeaturedOfferRevenueHourlySum, Integer FeaturedOfferImpressionsSum, String FeaturedOfferImpressionsHourlySum, Integer FeaturedOfferClicksSum, String FeaturedOfferClicksHourlySum, Integer FeaturedOfferConversionsSum, String FeaturedOfferConversionsHourlySum, Double TJMOfferwallRevenueSum, String TJMOfferwallRevenueHourlySum, Integer TJMOfferwallImpressionsSum, String TJMOfferwallImpressionsHourlySum, Integer TJMOfferwallClicksSum, String TJMOfferwallClicksHourlySum, Integer TJMOfferwallConversionsSum, String TJMOfferwallConversionsHourlySum, Double DirectPlayRevenueSum, String DirectPlayRevenueHourlySum, Integer DirectPlayImpressionsSum, String DirectPlayImpressionsHourlySum, Integer DirectPlayClicksSum, String DirectPlayClicksHourlySum, Integer DirectPlayConversionsSum, String DirectPlayConversionsHourlySum) {
        this.id = id;
        this.Date = Date;
        this.AppCount = AppCount;
        this.PaidInstallsSum = PaidInstallsSum;
        this.PaidInstallsHourlySum = PaidInstallsHourlySum;
        this.PaidClicksSum = PaidClicksSum;
        this.PaidClicksHourlySum = PaidClicksHourlySum;
        this.SpendSum = SpendSum;
        this.SpendHourlySum = SpendHourlySum;
        this.SessionsSum = SessionsSum;
        this.SessionsHourlySum = SessionsHourlySum;
        this.NewUsersSum = NewUsersSum;
        this.NewUsersHourlySum = NewUsersHourlySum;
        this.DailyActiveUsersSum = DailyActiveUsersSum;
        this.OfferwallRevenueSum = OfferwallRevenueSum;
        this.OfferwallRevenueHourlySum = OfferwallRevenueHourlySum;
        this.OfferwallImpressionsSum = OfferwallImpressionsSum;
        this.OfferwallImpressionsHourlySum = OfferwallImpressionsHourlySum;
        this.OfferwallClicksSum = OfferwallClicksSum;
        this.OfferwallClicksHourlySum = OfferwallClicksHourlySum;
        this.OfferwallConversionsSum = OfferwallConversionsSum;
        this.OfferwallConversionsHourlySum = OfferwallConversionsHourlySum;
        this.FeaturedOfferRevenueSum = FeaturedOfferRevenueSum;
        this.FeaturedOfferRevenueHourlySum = FeaturedOfferRevenueHourlySum;
        this.FeaturedOfferImpressionsSum = FeaturedOfferImpressionsSum;
        this.FeaturedOfferImpressionsHourlySum = FeaturedOfferImpressionsHourlySum;
        this.FeaturedOfferClicksSum = FeaturedOfferClicksSum;
        this.FeaturedOfferClicksHourlySum = FeaturedOfferClicksHourlySum;
        this.FeaturedOfferConversionsSum = FeaturedOfferConversionsSum;
        this.FeaturedOfferConversionsHourlySum = FeaturedOfferConversionsHourlySum;
        this.TJMOfferwallRevenueSum = TJMOfferwallRevenueSum;
        this.TJMOfferwallRevenueHourlySum = TJMOfferwallRevenueHourlySum;
        this.TJMOfferwallImpressionsSum = TJMOfferwallImpressionsSum;
        this.TJMOfferwallImpressionsHourlySum = TJMOfferwallImpressionsHourlySum;
        this.TJMOfferwallClicksSum = TJMOfferwallClicksSum;
        this.TJMOfferwallClicksHourlySum = TJMOfferwallClicksHourlySum;
        this.TJMOfferwallConversionsSum = TJMOfferwallConversionsSum;
        this.TJMOfferwallConversionsHourlySum = TJMOfferwallConversionsHourlySum;
        this.DirectPlayRevenueSum = DirectPlayRevenueSum;
        this.DirectPlayRevenueHourlySum = DirectPlayRevenueHourlySum;
        this.DirectPlayImpressionsSum = DirectPlayImpressionsSum;
        this.DirectPlayImpressionsHourlySum = DirectPlayImpressionsHourlySum;
        this.DirectPlayClicksSum = DirectPlayClicksSum;
        this.DirectPlayClicksHourlySum = DirectPlayClicksHourlySum;
        this.DirectPlayConversionsSum = DirectPlayConversionsSum;
        this.DirectPlayConversionsHourlySum = DirectPlayConversionsHourlySum;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getDate() {
        return Date;
    }

    public void setDate(String Date) {
        this.Date = Date;
    }

    public Integer getAppCount() {
        return AppCount;
    }

    public void setAppCount(Integer AppCount) {
        this.AppCount = AppCount;
    }

    public Integer getPaidInstallsSum() {
        return PaidInstallsSum;
    }

    public void setPaidInstallsSum(Integer PaidInstallsSum) {
        this.PaidInstallsSum = PaidInstallsSum;
    }

    public String getPaidInstallsHourlySum() {
        return PaidInstallsHourlySum;
    }

    public void setPaidInstallsHourlySum(String PaidInstallsHourlySum) {
        this.PaidInstallsHourlySum = PaidInstallsHourlySum;
    }

    public Integer getPaidClicksSum() {
        return PaidClicksSum;
    }

    public void setPaidClicksSum(Integer PaidClicksSum) {
        this.PaidClicksSum = PaidClicksSum;
    }

    public String getPaidClicksHourlySum() {
        return PaidClicksHourlySum;
    }

    public void setPaidClicksHourlySum(String PaidClicksHourlySum) {
        this.PaidClicksHourlySum = PaidClicksHourlySum;
    }

    public Double getSpendSum() {
        return SpendSum;
    }

    public void setSpendSum(Double SpendSum) {
        this.SpendSum = SpendSum;
    }

    public String getSpendHourlySum() {
        return SpendHourlySum;
    }

    public void setSpendHourlySum(String SpendHourlySum) {
        this.SpendHourlySum = SpendHourlySum;
    }

    public Integer getSessionsSum() {
        return SessionsSum;
    }

    public void setSessionsSum(Integer SessionsSum) {
        this.SessionsSum = SessionsSum;
    }

    public String getSessionsHourlySum() {
        return SessionsHourlySum;
    }

    public void setSessionsHourlySum(String SessionsHourlySum) {
        this.SessionsHourlySum = SessionsHourlySum;
    }

    public Integer getNewUsersSum() {
        return NewUsersSum;
    }

    public void setNewUsersSum(Integer NewUsersSum) {
        this.NewUsersSum = NewUsersSum;
    }

    public String getNewUsersHourlySum() {
        return NewUsersHourlySum;
    }

    public void setNewUsersHourlySum(String NewUsersHourlySum) {
        this.NewUsersHourlySum = NewUsersHourlySum;
    }

    public Integer getDailyActiveUsersSum() {
        return DailyActiveUsersSum;
    }

    public void setDailyActiveUsersSum(Integer DailyActiveUsersSum) {
        this.DailyActiveUsersSum = DailyActiveUsersSum;
    }

    public Double getOfferwallRevenueSum() {
        return OfferwallRevenueSum;
    }

    public void setOfferwallRevenueSum(Double OfferwallRevenueSum) {
        this.OfferwallRevenueSum = OfferwallRevenueSum;
    }

    public String getOfferwallRevenueHourlySum() {
        return OfferwallRevenueHourlySum;
    }

    public void setOfferwallRevenueHourlySum(String OfferwallRevenueHourlySum) {
        this.OfferwallRevenueHourlySum = OfferwallRevenueHourlySum;
    }

    public Integer getOfferwallImpressionsSum() {
        return OfferwallImpressionsSum;
    }

    public void setOfferwallImpressionsSum(Integer OfferwallImpressionsSum) {
        this.OfferwallImpressionsSum = OfferwallImpressionsSum;
    }

    public String getOfferwallImpressionsHourlySum() {
        return OfferwallImpressionsHourlySum;
    }

    public void setOfferwallImpressionsHourlySum(String OfferwallImpressionsHourlySum) {
        this.OfferwallImpressionsHourlySum = OfferwallImpressionsHourlySum;
    }

    public Integer getOfferwallClicksSum() {
        return OfferwallClicksSum;
    }

    public void setOfferwallClicksSum(Integer OfferwallClicksSum) {
        this.OfferwallClicksSum = OfferwallClicksSum;
    }

    public String getOfferwallClicksHourlySum() {
        return OfferwallClicksHourlySum;
    }

    public void setOfferwallClicksHourlySum(String OfferwallClicksHourlySum) {
        this.OfferwallClicksHourlySum = OfferwallClicksHourlySum;
    }

    public Integer getOfferwallConversionsSum() {
        return OfferwallConversionsSum;
    }

    public void setOfferwallConversionsSum(Integer OfferwallConversionsSum) {
        this.OfferwallConversionsSum = OfferwallConversionsSum;
    }

    public String getOfferwallConversionsHourlySum() {
        return OfferwallConversionsHourlySum;
    }

    public void setOfferwallConversionsHourlySum(String OfferwallConversionsHourlySum) {
        this.OfferwallConversionsHourlySum = OfferwallConversionsHourlySum;
    }

    public Double getFeaturedOfferRevenueSum() {
        return FeaturedOfferRevenueSum;
    }

    public void setFeaturedOfferRevenueSum(Double FeaturedOfferRevenueSum) {
        this.FeaturedOfferRevenueSum = FeaturedOfferRevenueSum;
    }

    public String getFeaturedOfferRevenueHourlySum() {
        return FeaturedOfferRevenueHourlySum;
    }

    public void setFeaturedOfferRevenueHourlySum(String FeaturedOfferRevenueHourlySum) {
        this.FeaturedOfferRevenueHourlySum = FeaturedOfferRevenueHourlySum;
    }

    public Integer getFeaturedOfferImpressionsSum() {
        return FeaturedOfferImpressionsSum;
    }

    public void setFeaturedOfferImpressionsSum(Integer FeaturedOfferImpressionsSum) {
        this.FeaturedOfferImpressionsSum = FeaturedOfferImpressionsSum;
    }

    public String getFeaturedOfferImpressionsHourlySum() {
        return FeaturedOfferImpressionsHourlySum;
    }

    public void setFeaturedOfferImpressionsHourlySum(String FeaturedOfferImpressionsHourlySum) {
        this.FeaturedOfferImpressionsHourlySum = FeaturedOfferImpressionsHourlySum;
    }

    public Integer getFeaturedOfferClicksSum() {
        return FeaturedOfferClicksSum;
    }

    public void setFeaturedOfferClicksSum(Integer FeaturedOfferClicksSum) {
        this.FeaturedOfferClicksSum = FeaturedOfferClicksSum;
    }

    public String getFeaturedOfferClicksHourlySum() {
        return FeaturedOfferClicksHourlySum;
    }

    public void setFeaturedOfferClicksHourlySum(String FeaturedOfferClicksHourlySum) {
        this.FeaturedOfferClicksHourlySum = FeaturedOfferClicksHourlySum;
    }

    public Integer getFeaturedOfferConversionsSum() {
        return FeaturedOfferConversionsSum;
    }

    public void setFeaturedOfferConversionsSum(Integer FeaturedOfferConversionsSum) {
        this.FeaturedOfferConversionsSum = FeaturedOfferConversionsSum;
    }

    public String getFeaturedOfferConversionsHourlySum() {
        return FeaturedOfferConversionsHourlySum;
    }

    public void setFeaturedOfferConversionsHourlySum(String FeaturedOfferConversionsHourlySum) {
        this.FeaturedOfferConversionsHourlySum = FeaturedOfferConversionsHourlySum;
    }

    public Double getTJMOfferwallRevenueSum() {
        return TJMOfferwallRevenueSum;
    }

    public void setTJMOfferwallRevenueSum(Double TJMOfferwallRevenueSum) {
        this.TJMOfferwallRevenueSum = TJMOfferwallRevenueSum;
    }

    public String getTJMOfferwallRevenueHourlySum() {
        return TJMOfferwallRevenueHourlySum;
    }

    public void setTJMOfferwallRevenueHourlySum(String TJMOfferwallRevenueHourlySum) {
        this.TJMOfferwallRevenueHourlySum = TJMOfferwallRevenueHourlySum;
    }

    public Integer getTJMOfferwallImpressionsSum() {
        return TJMOfferwallImpressionsSum;
    }

    public void setTJMOfferwallImpressionsSum(Integer TJMOfferwallImpressionsSum) {
        this.TJMOfferwallImpressionsSum = TJMOfferwallImpressionsSum;
    }

    public String getTJMOfferwallImpressionsHourlySum() {
        return TJMOfferwallImpressionsHourlySum;
    }

    public void setTJMOfferwallImpressionsHourlySum(String TJMOfferwallImpressionsHourlySum) {
        this.TJMOfferwallImpressionsHourlySum = TJMOfferwallImpressionsHourlySum;
    }

    public Integer getTJMOfferwallClicksSum() {
        return TJMOfferwallClicksSum;
    }

    public void setTJMOfferwallClicksSum(Integer TJMOfferwallClicksSum) {
        this.TJMOfferwallClicksSum = TJMOfferwallClicksSum;
    }

    public String getTJMOfferwallClicksHourlySum() {
        return TJMOfferwallClicksHourlySum;
    }

    public void setTJMOfferwallClicksHourlySum(String TJMOfferwallClicksHourlySum) {
        this.TJMOfferwallClicksHourlySum = TJMOfferwallClicksHourlySum;
    }

    public Integer getTJMOfferwallConversionsSum() {
        return TJMOfferwallConversionsSum;
    }

    public void setTJMOfferwallConversionsSum(Integer TJMOfferwallConversionsSum) {
        this.TJMOfferwallConversionsSum = TJMOfferwallConversionsSum;
    }

    public String getTJMOfferwallConversionsHourlySum() {
        return TJMOfferwallConversionsHourlySum;
    }

    public void setTJMOfferwallConversionsHourlySum(String TJMOfferwallConversionsHourlySum) {
        this.TJMOfferwallConversionsHourlySum = TJMOfferwallConversionsHourlySum;
    }

    public Double getDirectPlayRevenueSum() {
        return DirectPlayRevenueSum;
    }

    public void setDirectPlayRevenueSum(Double DirectPlayRevenueSum) {
        this.DirectPlayRevenueSum = DirectPlayRevenueSum;
    }

    public String getDirectPlayRevenueHourlySum() {
        return DirectPlayRevenueHourlySum;
    }

    public void setDirectPlayRevenueHourlySum(String DirectPlayRevenueHourlySum) {
        this.DirectPlayRevenueHourlySum = DirectPlayRevenueHourlySum;
    }

    public Integer getDirectPlayImpressionsSum() {
        return DirectPlayImpressionsSum;
    }

    public void setDirectPlayImpressionsSum(Integer DirectPlayImpressionsSum) {
        this.DirectPlayImpressionsSum = DirectPlayImpressionsSum;
    }

    public String getDirectPlayImpressionsHourlySum() {
        return DirectPlayImpressionsHourlySum;
    }

    public void setDirectPlayImpressionsHourlySum(String DirectPlayImpressionsHourlySum) {
        this.DirectPlayImpressionsHourlySum = DirectPlayImpressionsHourlySum;
    }

    public Integer getDirectPlayClicksSum() {
        return DirectPlayClicksSum;
    }

    public void setDirectPlayClicksSum(Integer DirectPlayClicksSum) {
        this.DirectPlayClicksSum = DirectPlayClicksSum;
    }

    public String getDirectPlayClicksHourlySum() {
        return DirectPlayClicksHourlySum;
    }

    public void setDirectPlayClicksHourlySum(String DirectPlayClicksHourlySum) {
        this.DirectPlayClicksHourlySum = DirectPlayClicksHourlySum;
    }

    public Integer getDirectPlayConversionsSum() {
        return DirectPlayConversionsSum;
    }

    public void setDirectPlayConversionsSum(Integer DirectPlayConversionsSum) {
        this.DirectPlayConversionsSum = DirectPlayConversionsSum;
    }

    public String getDirectPlayConversionsHourlySum() {
        return DirectPlayConversionsHourlySum;
    }

    public void setDirectPlayConversionsHourlySum(String DirectPlayConversionsHourlySum) {
        this.DirectPlayConversionsHourlySum = DirectPlayConversionsHourlySum;
    }

    // KEEP METHODS - put your custom methods here
    public void setConvertArraysToString() {
        setPaidInstallsHourlySum(TapjoyUtils.convertIntArrayToString(getPaidInstallsHourly()));
        setPaidClicksHourlySum(TapjoyUtils.convertIntArrayToString(getPaidClicksHourly()));
        setSpendHourlySum(TapjoyUtils.convertDoubleArrayToString(getSpendHourly()));
        setSessionsHourlySum(TapjoyUtils.convertIntArrayToString(getSessionsHourly()));
        setNewUsersHourlySum(TapjoyUtils.convertIntArrayToString(getNewUsersHourly()));
        setOfferwallRevenueHourlySum(TapjoyUtils.convertDoubleArrayToString(getOfferwallRevenueHourly()));
        setOfferwallImpressionsHourlySum(TapjoyUtils.convertIntArrayToString(getOfferwallImpressionsHourly()));
        setOfferwallClicksHourlySum(TapjoyUtils.convertIntArrayToString(getOfferwallClicksHourly()));
        setOfferwallConversionsHourlySum(TapjoyUtils.convertIntArrayToString(getOfferwallConversionsHourly()));
        setFeaturedOfferRevenueHourlySum(TapjoyUtils.convertDoubleArrayToString(getFeaturedOfferRevenueHourly()));
        setFeaturedOfferImpressionsHourlySum(TapjoyUtils.convertIntArrayToString(getFeaturedOfferImpressionsHourly()));
        setFeaturedOfferClicksHourlySum(TapjoyUtils.convertIntArrayToString(getFeaturedOfferClicksHourly()));
        setFeaturedOfferConversionsHourlySum(TapjoyUtils.convertIntArrayToString(getFeaturedOfferConversionsHourly()));
        setTJMOfferwallRevenueHourlySum(TapjoyUtils.convertDoubleArrayToString(getTJMOfferwallRevenueHourly()));
        setTJMOfferwallImpressionsHourlySum(TapjoyUtils.convertIntArrayToString(getTJMOfferwallImpressionsHourly()));
        setTJMOfferwallClicksHourlySum(TapjoyUtils.convertIntArrayToString(getTJMOfferwallClicksHourly()));
        setTJMOfferwallConversionsHourlySum(TapjoyUtils.convertIntArrayToString(getTJMOfferwallConversionsHourly()));
        setDirectPlayRevenueHourlySum(TapjoyUtils.convertDoubleArrayToString(getDirectPlayRevenueHourly()));
        setDirectPlayImpressionsHourlySum(TapjoyUtils.convertIntArrayToString(getDirectPlayImpressionsHourly()));
        setDirectPlayClicksHourlySum(TapjoyUtils.convertIntArrayToString(getDirectPlayClicksHourly()));
        setDirectPlayConversionsHourlySum(TapjoyUtils.convertIntArrayToString(getDirectPlayConversionsHourly()));
    }

    public int[] getPaidInstallsHourly() {
        return PaidInstallsHourly;
    }

    public void setPaidInstallsHourly(int[] paidInstallsHourly) {
        PaidInstallsHourly = paidInstallsHourly;
    }

    public int[] getPaidClicksHourly() {
        return PaidClicksHourly;
    }

    public void setPaidClicksHourly(int[] paidClicksHourly) {
        PaidClicksHourly = paidClicksHourly;
    }

    public double[] getSpendHourly() {
        return SpendHourly;
    }

    public void setSpendHourly(double[] spendHourly) {
        SpendHourly = spendHourly;
    }

    public int[] getSessionsHourly() {
        return SessionsHourly;
    }

    public void setSessionsHourly(int[] sessionsHourly) {
        SessionsHourly = sessionsHourly;
    }

    public int[] getNewUsersHourly() {
        return NewUsersHourly;
    }

    public void setNewUsersHourly(int[] newUsersHourly) {
        NewUsersHourly = newUsersHourly;
    }

    public double[] getOfferwallRevenueHourly() {
        return OfferwallRevenueHourly;
    }

    public void setOfferwallRevenueHourly(double[] offerwallRevenueHourly) {
        OfferwallRevenueHourly = offerwallRevenueHourly;
    }

    public int[] getOfferwallImpressionsHourly() {
        return OfferwallImpressionsHourly;
    }

    public void setOfferwallImpressionsHourly(int[] offerwallImpressionsHourly) {
        OfferwallImpressionsHourly = offerwallImpressionsHourly;
    }

    public int[] getOfferwallClicksHourly() {
        return OfferwallClicksHourly;
    }

    public void setOfferwallClicksHourly(int[] offerwallClicksHourly) {
        OfferwallClicksHourly = offerwallClicksHourly;
    }

    public int[] getOfferwallConversionsHourly() {
        return OfferwallConversionsHourly;
    }

    public void setOfferwallConversionsHourly(int[] offerwallConversionsHourly) {
        OfferwallConversionsHourly = offerwallConversionsHourly;
    }

    public double[] getFeaturedOfferRevenueHourly() {
        return FeaturedOfferRevenueHourly;
    }

    public void setFeaturedOfferRevenueHourly(double[] featuredOfferRevenueHourly) {
        FeaturedOfferRevenueHourly = featuredOfferRevenueHourly;
    }

    public int[] getFeaturedOfferImpressionsHourly() {
        return FeaturedOfferImpressionsHourly;
    }

    public void setFeaturedOfferImpressionsHourly(int[] featuredOfferImpressionsHourly) {
        FeaturedOfferImpressionsHourly = featuredOfferImpressionsHourly;
    }

    public int[] getFeaturedOfferClicksHourly() {
        return FeaturedOfferClicksHourly;
    }

    public void setFeaturedOfferClicksHourly(int[] featuredOfferClicksHourly) {
        FeaturedOfferClicksHourly = featuredOfferClicksHourly;
    }

    public int[] getFeaturedOfferConversionsHourly() {
        return FeaturedOfferConversionsHourly;
    }

    public void setFeaturedOfferConversionsHourly(int[] featuredOfferConversionsHourly) {
        FeaturedOfferConversionsHourly = featuredOfferConversionsHourly;
    }

    public double[] getTJMOfferwallRevenueHourly() {
        return TJMOfferwallRevenueHourly;
    }

    public void setTJMOfferwallRevenueHourly(double[] TJMOfferwallRevenueHourly) {
        this.TJMOfferwallRevenueHourly = TJMOfferwallRevenueHourly;
    }

    public int[] getTJMOfferwallImpressionsHourly() {
        return TJMOfferwallImpressionsHourly;
    }

    public void setTJMOfferwallImpressionsHourly(int[] TJMOfferwallImpressionsHourly) {
        this.TJMOfferwallImpressionsHourly = TJMOfferwallImpressionsHourly;
    }

    public int[] getTJMOfferwallClicksHourly() {
        return TJMOfferwallClicksHourly;
    }

    public void setTJMOfferwallClicksHourly(int[] TJMOfferwallClicksHourly) {
        this.TJMOfferwallClicksHourly = TJMOfferwallClicksHourly;
    }

    public int[] getTJMOfferwallConversionsHourly() {
        return TJMOfferwallConversionsHourly;
    }

    public void setTJMOfferwallConversionsHourly(int[] TJMOfferwallConversionsHourly) {
        this.TJMOfferwallConversionsHourly = TJMOfferwallConversionsHourly;
    }

    public double[] getDirectPlayRevenueHourly() {
        return DirectPlayRevenueHourly;
    }

    public void setDirectPlayRevenueHourly(double[] directPlayRevenueHourly) {
        DirectPlayRevenueHourly = directPlayRevenueHourly;
    }

    public int[] getDirectPlayImpressionsHourly() {
        return DirectPlayImpressionsHourly;
    }

    public void setDirectPlayImpressionsHourly(int[] directPlayImpressionsHourly) {
        DirectPlayImpressionsHourly = directPlayImpressionsHourly;
    }

    public int[] getDirectPlayClicksHourly() {
        return DirectPlayClicksHourly;
    }

    public void setDirectPlayClicksHourly(int[] directPlayClicksHourly) {
        DirectPlayClicksHourly = directPlayClicksHourly;
    }

    public int[] getDirectPlayConversionsHourly() {
        return DirectPlayConversionsHourly;
    }

    public void setDirectPlayConversionsHourly(int[] directPlayConversionsHourly) {
        DirectPlayConversionsHourly = directPlayConversionsHourly;
    }
    // KEEP METHODS END

}
